Getting install path

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -7,12 +7,16 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+  windows:
     runs-on: windows-latest
 
     steps:
     - uses: actions/checkout@v4
     - name: Install SFML
-      run: sudo apt-get install libsfml-dev
+      run: choco install sfml
+    - name: Check SFML installation
+      run: where sfml-graphics.lib
+    - name: Check SFML installation
+      run: where sfml-graphics.lib || echo "SFML not found!"
     - name: Compile with MSVC
-      run: cl /EHsc /std:c++17 /I "C:\C++ Libraries\SFML-3.0.0-windows-vc17-32-bit\SFML-3.0.0\include" main.cpp /link "/LIBPATH:C:\C++ Libraries\SFML-3.0.0-windows-vc17-32-bit\SFML-3.0.0\lib" sfml-graphics.lib sfml-window.lib sfml-system.lib
+      run: cl /EHsc /std:c++17 /I "C:\C++ Libraries\SFML-3.0.0-windows-vc17-32-bit\SFML-3.0.0\include" main.cpp /link where sfml-graphics.lib sfml-graphics.lib sfml-window.lib sfml-system.lib
